### ISSUE TITLE
Specify a path for the configuration files

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/Monitoring#78]
It seems that it is not possible to use a configuration dir different from /etc/zabbix. It would be nice to be able to pass the path as option to the command line

**Comment by jose-sanchezm** [comment]
Latest version of Mesos, OCCI and OpenStack probes accept a -l parameter that should point to the configuration folder. For example 'java -jar com.indigo.mesosprobe.MesosThread -cp /usr/share/java/zabbix/mesos-zabbix-probe.jar -l /root/zabbix_config' will try to find the configuration file in /root/zabbix-config/mesosprobe.properties

I'm working in some other probes and in a launcher script to simplify this
