### ISSUE TITLE
Cloud providers discovery

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/Monitoring#79]
Why do you need to specify the list of providers in the configuration file oszones.yml?
The list of providers is available in CMDB:
````
# curl -X GET http(s)://cmdb_endpoint/provider/list
{"total_rows":14,"offset":4,"rows":[
{"id":"provider-IFCA-LCG2","key":["provider"],"value":{"name":"IFCA-LCG2"}},
{"id":"provider-RECAS-BARI","key":["provider"],"value":{"name":"RECAS-BARI"}}
]}
````

**Comment by jose-sanchezm** [comment]
Unless protocol, identity provider and project information comes from the CMDB, we need some way to specify this per provider. As such, oszones.yml is still needed.
