### ISSUE TITLE
MesosZabbixProbe RPM does not work on CentOS 7.5

### ISSUE THREAD

**Issue by alexcos78** [indigo-dc/Monitoring#83]
MesosZabbixProbe rpm does not work on CentOS 7.5

yum install https://github.com/indigo-dc/Monitoring/raw/1.02/zabbix-probes/mesos-zabbix-probe/MesosZabbixProbe-1.01-1.noarch.rpm

or the new version

yum install https://github.com/indigo-dc/Monitoring/raw/master/zabbix-probes/mesos-zabbix-probe/MesosZabbixProbe-1.2-1.noarch.rpm

give the same error

Transaction check error:
  file /usr/bin from install of MesosZabbixProbe-1.01-1.noarch conflicts with file from package filesystem-3.2-25.el7.x86_64

and

Transaction check error:
  file /usr/bin from install of MesosZabbixProbe-1.2-1.noarch conflicts with file from package filesystem-3.2-25.el7.x86_64

**Comment by jose-sanchezm** [comment]
It should be fixed now by pull request https://github.com/indigo-dc/Monitoring/pull/84

**Comment by jose-sanchezm** [comment]
Fix merged into master
